# Generated by Django 6.0 on 2025-12-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="colout",
            new_name="colour",
        ),
    ]
