# Generated by Django 6.0 on 2025-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0002_rename_colout_item_colour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="action_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
